package com.game.framework;

public enum ObjectID {
	Player(), 
	BlueCannon(),
	RedCannon(),
	YellowCannon(),
	PurpleCannon(),
	BlackCannon(),
	WhiteCannon(),
	TurretCannon(),
	MenuCannon(),
	BossCannon(),
	Wall(), 
	BattleDoor(),
	Checkpoint(),
	AmmoBox(),
	LifeHeart(),
	LevelFinish(),
	BasicBullet(),
	FastBullet(),
	EmpBullet(), 
	BouncyBullet(),
	TargetingBullet(),
	TurretMultiBullet(),
	LandMine(), 
	Turret(),
	RedTank(),
	YellowTank(),
	PurpleTank(),
	BlackTank(),
	WhiteTank(),
	BossTank(),
	LeftMenuTank(),
	RightMenuTank(), 
	Trail();
}
